### PR TITLE
.added bar charts to display data in the analysis section

### PR DESCRIPTION
**Pull request by shaunak-09**
I have added bar charts to display the tags solved and verdict distribution by the user in the  analysis section.

### CODE REVIEW

**Comment by shaunak-09** [comment]
Why is it showing all checks failed?

**Comment by shrinish123** [comment]
Please remove all the warnings and make a commit. THe warnings are treated as errors and hence the build failed.

**Comment by shrinish123** [comment]
Wow. I checked it. Looks great. I will merge this one. If you wish contribute more on this , you can keep continue working on it. 
Thanks a lot for your contribution.

**Comment by shaunak-09** [comment]
Thanks, I will try to implement some diffferent type of graph for the verdict distribution later on.

**Pull request merged**
