### PR TITLE
Enhanced Table moved to another Component

### PR DESCRIPTION
**Pull request by MaYaNkKashyap681**
Moved Enhanced Table Into a different file and made it a component.

### CODE REVIEW

**Comment by shrinish123** [comment]
@MaYaNkKashyap681 there are some merge conflicts here right now ,just resolve those and make a commit on this PR

**Comment by MaYaNkKashyap681** [comment]
> @MaYaNkKashyap681 there are some merge conflicts here right now ,just resolve those and make a commit on this PR

I have not changed not even a single line in this code.

**Comment by MaYaNkKashyap681** [comment]
> > @MaYaNkKashyap681 there are some merge conflicts here right now ,just resolve those and make a commit on this PR
> 
> I have not changed not even a single line in the file Analysis.js.

**Comment by MaYaNkKashyap681** [comment]
Now is it okay.

**Comment by shrinish123** [comment]
Its still showing conflicts in package.lock json file , and without resolving the conflicts even I cannot merge them

**Comment by shrinish123** [comment]
> > @MaYaNkKashyap681 there are some merge conflicts here right now ,just resolve those and make a commit on this PR
> 
> I have not changed not even a single line in this code.

Ya you have not changed it ,but some other people who contributed did , and hence a good practice is to work in a separate branch in your local then git pull the current version and then git merge the main branch to the branch you are working upon.
From next time, its good to follow this workflow.

**Comment by MaYaNkKashyap681** [comment]
Now is it ok?

**Comment by MaYaNkKashyap681** [comment]
> > > @MaYaNkKashyap681 there are some merge conflicts here right now ,just resolve those and make a commit on this PR
> > 
> > 
> > I have not changed not even a single line in this code.
> 
> Ya you have not changed it ,but some other people who contributed did , and hence a good practice is to work in a separate branch in your local then git pull the current version and then git merge the main branch to the branch you are working upon. From next time, its good to follow this workflow.

ya sure

**Comment by shrinish123** [comment]
Well I guess its solved ,I ll merge it , Thanks for your contribution

**Comment by MaYaNkKashyap681** [comment]
> Well I guess its solved ,I ll merge it , Thanks for your contribution

Your welcome

**Pull request merged**
